---
# This playbook install kubeadm
- name: Install Kubernetes master
  hosts: controller
  remote_user: pi
  become: yes
  become_method: sudo
  tags:
    - master
  roles:
    - master

- name: Install nodes
  hosts: nodes
  remote_user: pi
  become: yes
  become_method: sudo
  tags: 
    - slaves
  roles:
    - slaves

- name: Install weave network
  hosts: controller
  remote_user: pi
  become: yes
  become_method: sudo
  tags: 
    - network
  roles:
    - network
  tags: 
    - config
  roles:
    - config

- name: Install config
  hosts: controller
  remote_user: pi
  become: yes
  become_method: sudo
  tags: 
    - config
  roles:
    - config
