---

- file:
    path: /usr/local/kubernetes
    state: directory
    owner: root
    group: root
    mode: 0755

- copy:
    src: files/get.docker.sh
    dest: /usr/local/kubernetes/get.docker.sh
    owner: root
    group: root
    mode: 0744
  register: getdocker

- name: Execute get docker
  shell: /usr/local/kubernetes/get.docker.sh
  become: yes
  when: getdocker | changed

- name: Adding existing user pi to group docker
  user: name=pi
        groups=docker
        append=yes


##Disabling Swap
- name: Check that if backup file exist, then skip disable swap
  stat:
    path: /boot/cmdline_backup.txt
  register: stat_result

- name: Disabling swap 1
  shell: dphys-swapfile swapoff
  become: yes
  when: stat_result.stat.exists == False

- name: Disabling swap 2
  shell: dphys-swapfile uninstall
  become: yes
  when: stat_result.stat.exists == False

- name: Disabling swap 3
  shell: update-rc.d dphys-swapfile remove
  become: yes
  when: stat_result.stat.exists == False

- copy:
    src: /boot/cmdline.txt
    dest: /boot/cmdline_backup.txt
    owner: root
    group: root
    remote_src: yes
    mode: 0744
  when: stat_result.stat.exists == False

- shell: head -n1 /boot/cmdline.txt
  register: cat_contents
  when: stat_result.stat.exists == False

# if you encounter problems, try changing cgroup_memory=1 to cgroup_enable=memory.
- template:
    src: templates/cmdline.txt.tmpl
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: 0755
  when: stat_result.stat.exists == False

#Add kubernetes repo

- name: Add an Apt signing key, will not download if present
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: Add kubernetes repo
  command: touch /etc/apt/sources.list.d/kubernetes.list
- lineinfile: dest="/etc/apt/sources.list.d/kubernetes.list" line="{{item}}"
  with_items:
    - "deb http://apt.kubernetes.io/ kubernetes-xenial main"

- name: update cache
  apt: update_cache=yes

- debug: msg="You need to reboot the raspberry pi now!"
